<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5dd03418-3156-4635-81d8-fbfe490f7165</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDV.Dominio\PDV.Dominio.csproj" />
    <ProjectReference Include="..\PDV.Infraestrutura\PDV.Infraestrutura.csproj" />
    <ProjectReference Include="..\PDV.Repositorio\PDV.Repositorio.csproj" />
    <ProjectReference Include="..\PDV.Servico\PDV.Servico.csproj" />
  </ItemGroup>

</Project>
