// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PDV.Infraestrutura.Contexto;

#nullable disable

namespace PDV.Infraestrutura.Migracoes
{
    [DbContext(typeof(PdvDbContext))]
    partial class PdvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PDV.Dominio.Entidades.ConfiguracaoLoja", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<bool>("AlertaEstoqueBaixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("stock_alerts");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<string>("ComprovanteCabecalho")
                        .HasColumnType("text")
                        .HasColumnName("receipt_header");

                    b.Property<bool>("ComprovanteIncluirLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("receipt_include_logo");

                    b.Property<bool>("ComprovanteMostrarDadosFiscais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("receipt_show_fiscal_data");

                    b.Property<string>("ComprovanteRodape")
                        .HasColumnType("text")
                        .HasColumnName("receipt_footer");

                    b.Property<string>("EnderecoLoja")
                        .HasColumnType("text")
                        .HasColumnName("store_address");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<bool>("ImpressaoAutomatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_print");

                    b.Property<bool>("ImpressoraCorteAutomatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("printer_auto_cut");

                    b.Property<string>("ImpressoraLarguraPapel")
                        .HasColumnType("text")
                        .HasColumnName("paper_width");

                    b.Property<string>("ImpressoraModelo")
                        .HasColumnType("text")
                        .HasColumnName("printer_model");

                    b.Property<string>("ImpressoraNome")
                        .HasColumnType("text")
                        .HasColumnName("printer_name");

                    b.Property<string>("LogoLoja")
                        .HasColumnType("text")
                        .HasColumnName("store_logo");

                    b.Property<string>("NomeLoja")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("BRINKPDV")
                        .HasColumnName("store_name");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<bool>("SomFinalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("checkout_sound");

                    b.Property<string>("TelefoneLoja")
                        .HasColumnType("text")
                        .HasColumnName("store_phone");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_phone_number_id");

                    b.Property<string>("WhatsAppToken")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_token");

                    b.HasKey("Id");

                    b.ToTable("store_settings", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.MovimentoCaixa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.OrdemServico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("Aparelho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<string>("ClienteId")
                        .HasColumnType("varchar")
                        .HasColumnName("client_id");

                    b.Property<string>("ContatoCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_contact");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("date")
                        .HasColumnName("exit_date");

                    b.Property<string>("EstadoAparelho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Bom")
                        .HasColumnName("device_condition");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("device_brand");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("device_model");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<DateOnly>("Prazo")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Média")
                        .HasColumnName("priority");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issue");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Orçamento")
                        .HasColumnName("status");

                    b.Property<string>("ItensServico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_items");

                    b.Property<string>("TipoAparelho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Outro")
                        .HasColumnName("device_type");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<int>("Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.Property<string>("Imagem")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.ServicoCatalogo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("PrecoPadrao")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("default_price");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Vendedor")
                        .HasColumnName("role");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Venda", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Itens")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("items");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("VendedorId")
                        .HasColumnType("varchar")
                        .HasColumnName("salesperson_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("VendedorId");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Vendedor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("commission");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<decimal>("TotalVendas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_sales");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("salespersons", (string)null);
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.OrdemServico", b =>
                {
                    b.HasOne("PDV.Dominio.Entidades.Cliente", "CadastroCliente")
                        .WithMany("Ordens")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CadastroCliente");
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Venda", b =>
                {
                    b.HasOne("PDV.Dominio.Entidades.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PDV.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Ordens");
                });
#pragma warning restore 612, 618
        }
    }
}
